### ISSUE TITLE
Actionsが通らない問題について

### ISSUE THREAD

**Issue by Luftalian** [Avi-67/Avi_67J_ComBoard#3]
`#include <SoftwareSerial.h>`
ここでエラーが出ている。
`SoftwareSerial.h`がsrcに含まれていないのが問題みたいなので直してほしいです。

**Comment by Watanabe1101** [comment]
修正しました

**Comment by Luftalian** [comment]
https://github.com/Avi-67/Avi_67J_ComBoard/commit/b1d494f8f6ec95187d14e4f8ab3ff3aafd1badba
