### ISSUE TITLE
複数ソフトウェアシリアルの実装

### ISSUE THREAD

**Issue by Luftalian** [Avi-67/Avi_67J_ComBoard#4]
1対1はできるが、1対3がうまくいかない。

**Comment by Luftalian** [comment]
`while`から`If`にしたけど、それはあまり正しくないかもしれない。
`Serial.available()`は`Serial.read()`で一個ずつ減るらしい。
だから、結局は`loop`で同じことになってる気がする。

**Comment by Luftalian** [comment]
並列処理を試してみてもいいかもしれない。
時間あったら、ブランチ切ってやってみてほしい。

**Comment by Luftalian** [comment]
[https://docs.arduino.cc/learn/built-in-libraries/software-serial#listen](https://docs.arduino.cc/learn/built-in-libraries/software-serial#listen)
ソフトウェアシリアルは、複数同時通信が不可能らしい。
`listen()`関数で頑張れば可能性はなくもない

**Comment by Luftalian** [comment]
[https://docs.arduino.cc/tutorials/communication/TwoPortReceive](https://docs.arduino.cc/tutorials/communication/TwoPortReceive)

これ参考にしたらできそう。

**Comment by Luftalian** [comment]
上の方法でできなかったら、[https://github.com/askn37/MultiUART](https://github.com/askn37/MultiUART)

上の方法を先に試してほしい。

**Comment by Watanabe1101** [comment]
whileからifに変えるとtweliteとの通信が失敗することが増えるので一旦mainは元のコードに戻しておく

**Comment by Watanabe1101** [comment]
listenを使ったテストコードはなぜかtweliteの通信も不安定になる

**Comment by Watanabe1101** [comment]
MulitUartで書いてみます

**Comment by Watanabe1101** [comment]
MultiUartはESPでは使えなさそう

**Comment by Watanabe1101** [comment]
コア0でGPSとtweliteのタスク、コア1で基板間通信のタスクを並列処理してみる

**Comment by Watanabe1101** [comment]
mainのコード以外だとtweliteが不安定になるバグを確認...(謎)
今日はここまで

**Comment by Watanabe1101** [comment]
明日やること
・tweliteの動作不安定原因特定
・コア1でのタスクのコードを書く
・コア0とコア１で並列処理を実装

**Comment by Luftalian** [comment]
> xTaskCreatePinnedToCore(GPSTask, "GPSTask", 1000, NULL, 1, NULL, 0);

これ1000じゃなくて8192のほうがいいと思う。

**Comment by Luftalian** [comment]
`xTaskCreatePinnedToCore(GPSTask, "GPSTask", 8192, NULL, 1, &task0, 0);`

**Comment by Watanabe1101** [comment]
確かにメインループも8192byteだしその方がいいね

**Comment by Watanabe1101** [comment]
修正しておく

**Comment by Luftalian** [comment]
> listenを使ったテストコードはなぜかtweliteの通信も不安定になる

このコードも上げてほしい

**Comment by Watanabe1101** [comment]
bug-serial-Watanabe1101ブランチの前のバージョン(d15943ba5719f3cf301c24a1b1e1b1daa1d8317d)なんだけど、他のブランチにあげたほうがいい？

**Comment by Watanabe1101** [comment]
tweliteについて正確に言うと、listenの時に不安定になるわけじゃなくてmainブランチのコード以外だと不安定になる

**Comment by Watanabe1101** [comment]
tweliteの不具合はPC側だった
listenのコードをもう一回試してみる

**Comment by Watanabe1101** [comment]
listenコード実行結果(各基板と接続しpを送信)
p
r from led

**Comment by Luftalian** [comment]
> bug-serial-Watanabe1101ブランチの前のバージョン(d15943ba5719f3cf301c24a1b1e1b1daa1d8317d)なんだけど、他のブランチにあげたほうがいい？

じゃあいい

**Comment by Luftalian** [comment]
> listenコード実行結果(各基板と接続しpを送信)
> 
> p
> 
> r from led

rが返ってくるのは正しい？

**Comment by Luftalian** [comment]
あと、何回かやって毎回led基板から返ってくるのか毎回変わるのか知りたい

**Comment by Watanabe1101** [comment]
listenでbranch作成しといた

**Comment by Watanabe1101** [comment]
rが返ってくるのは正しくない

**Comment by Watanabe1101** [comment]
Serialでピンを変えながら順番に通信するプログラムをやってみようとおもう

**Comment by Watanabe1101** [comment]
もしくはcore0でSerialとSerial3を使って、core1でSerial4を使うプログラムかな

**Comment by Watanabe1101** [comment]
led基板から帰ってくる値は","" "が多い
結論としては通信はうまくいってない

**Comment by Watanabe1101** [comment]
ピン変更は再起動しないとむずかしそうなので下の方針で行きます

**Comment by Luftalian** [comment]
上の方針でやってみた後でいいんだけど、ソフトウェアシリアルは、受け取ったときにlistenになってないと情報を捨てるようなので、ComBoardだけの変更では難しい気がしている。

そこで、ほかの基板が、ComBoardが受け取るまでコマンドを送り続けるようにしてみたい。
ComBoardの変更点としては、各基板からコマンドを受け取った後に再度同じコマンドを各基板に送るようにしてほしい。

**Comment by Watanabe1101** [comment]
1対2は出来た

preparation mode
p from log
p from para
 from para

 from para

**Comment by Luftalian** [comment]
もし可能だったら、ログ基板のメインの動作(計測、書き込み、削除)がうまく行っているか確認してほしい。

**Comment by Watanabe1101** [comment]
comブランチのコードテスト結果
[comtest.txt](https://github.com/Avi-67/Avi_67J_ComBoard/files/10838229/comtest.txt)

**Comment by Watanabe1101** [comment]
lコマンドの時に止まらない

**Comment by Watanabe1101** [comment]
pコマンドを送った時の波形
![logic(p)](https://user-images.githubusercontent.com/111119473/221529583-117a999c-3bd3-418a-b14e-fb6b49d10504.png)

**Comment by Watanabe1101** [comment]
拡大版
![スクリーンショット 2023-02-27 184757](https://user-images.githubusercontent.com/111119473/221530162-639fb89c-3d18-4290-96cd-5e77cd5e8ac8.png)
![logic(p)zoom1](https://user-images.githubusercontent.com/111119473/221530176-df847d02-305b-41e7-aa0c-c5f1dd63797f.png)

**Comment by Watanabe1101** [comment]
ログ基板からコマンドが返ってくるまでに80msくらいかかってる。
pを受けとってからjを返すまでは0.1msぐらい

**Comment by Watanabe1101** [comment]
lを送った時の波形
![スクリーンショット 2023-02-27 185317](https://user-images.githubusercontent.com/111119473/221531395-f1727b95-69a6-4895-9be7-daabb11f9d47.png)

**Comment by Watanabe1101** [comment]
com基板からは毎回ｊを返せてる

**Comment by Watanabe1101** [comment]
lコマンドのときは最初に帰ってくるまで6.5sくらい

**Comment by Watanabe1101** [comment]
led基板(mainブランチのコードそのまま)も追加したら通信できた
[comtest1.txt](https://github.com/Avi-67/Avi_67J_ComBoard/files/10838447/comtest1.txt)

**Comment by Watanabe1101** [comment]
後一つの通信はハードウェアシリアルを当てればいいからこれでいけそう

**Comment by Watanabe1101** [comment]
ログ基板のデータ(途中まで)
[platformio-device-monitor-230226-221206.log](https://github.com/Avi-67/Avi_67J_ComBoard/files/10867725/platformio-device-monitor-230226-221206.log)

**Comment by Watanabe1101** [comment]
ログ基板データ(途中まで)
[platformio-device-monitor-230302-134943.log](https://github.com/Avi-67/Avi_67J_ComBoard/files/10867737/platformio-device-monitor-230302-134943.log)

**Comment by Watanabe1101** [comment]
デリートしないver
[platformio-device-monitor-230302-160953.log](https://github.com/Avi-67/Avi_67J_ComBoard/files/10868520/platformio-device-monitor-230302-160953.log)

**Comment by Watanabe1101** [comment]
3ポートからのコマンド受信を確認
ログ基板以外のノイズがひどい...

**Comment by Luftalian** [comment]
最終
通信基板：各基板からの通信をlisten関数で変えながら受け取る。ある基板からデータを受け取ったらあらかじめ決めたコマンドをその基板に送信する。
ほかの基板：決まった周波数でデータを送り続ける。あらかじめ決めたコマンドが送られてきたら、それをやめる。
